name = "AnalyticSquarePulse"
uuid = "58b49aaa-f693-49aa-a6dc-f24ac989f3ba"
authors = ["Kyle Sherbert <kyle.sherbert@vt.edu> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SpecialMatrices = "928aab9d-ef52-54ac-8ca1-acd7ca42c160"
